// This file was auto-generated by SweetMock 0.9.36.0
// Changes to this file may be lost when the code is regenerated.

#nullable enable
// test
using global::SweetMock;
using System.Linq;

namespace System{
    /// <summary>
    ///    Mock implementation of <see cref="global::System.TimeProvider">TimeProvider</see>.
    ///    Should only be used for testing purposes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("SweetMock","0.9.36.0")]
    internal partial class MockOf_TimeProvider : TimeProvider{
        private const string _containerName = "global::System.TimeProvider";
#region Configuration
        /// <summary>
        ///    Configuration class for the mock.
        /// </summary>
        internal partial class MockConfig{
            private readonly MockOf_TimeProvider target;
            /// <summary>
            ///    Initializes the configuration for <see cref="global::System.TimeProvider">TimeProvider</see> instance of the MockConfig class
            /// </summary>
            /// <param name="target">The target mock class.</param>
            /// <param name="config">Optional configuration method.</param>
            public MockConfig(MockOf_TimeProvider target, System.Action<MockConfig>? config = null){
                this.target = target;

                var initial = TimeProvider.System;
                this.Initialize(initial);

                config?.Invoke(this);
            }

            public MockConfig Initialize(TimeProvider initial) =>
                this.GetUtcNow(call: () => initial.GetUtcNow())
                    .CreateTimer(call: (callback, state, time, period) => initial.CreateTimer(callback, state, time, period))
                    .GetTimestamp(call: () => initial.GetTimestamp())
                    .LocalTimeZone(get: () => initial.LocalTimeZone)
                    .TimestampFrequency(get: () => initial.TimestampFrequency);
        }
#endregion

#region Logging
        private global::SweetMock.CallLog _sweetMockCallLog = new global::SweetMock.CallLog();
        private void _log(global::SweetMock.ArgumentBase argument) {_sweetMockCallLog.Calls.Add(argument);}
        internal partial class MockConfig{
            internal MockConfig GetCallLogs(out TimeProvider_Logs callLog){
                callLog = new TimeProvider_Logs(target._sweetMockCallLog, target._sweetMockInstanceName);
                return this;
            }
        }
#endregion

#region Constructors
        global::SweetMock.MockOptions? _sweetMockOptions {get;set;}
        string _sweetMockInstanceName {get; set;} = "";

        public record TimeProvider_Arguments(
            global::System.String? InstanceName,
            global::System.String MethodSignature
        ) : ArgumentBase(_containerName, "TimeProvider", MethodSignature, InstanceName);

        internal protected MockOf_TimeProvider(System.Action<MockConfig>? config = null, global::SweetMock.MockOptions? options = null) : base(){
            _sweetMockOptions = options ?? global::SweetMock.MockOptions.Default;
            _sweetMockCallLog = _sweetMockOptions.Logger ?? _sweetMockCallLog;
            _sweetMockInstanceName = _sweetMockOptions.InstanceName ?? "TimeProvider";
            this._log(new TimeProvider_Arguments(_sweetMockInstanceName, "TimeProvider"));
            new MockConfig(this, config);
        }
#endregion

#region Method : CreateTimer
        public record CreateTimer_Arguments(
            global::System.String? InstanceName,
            global::System.String MethodSignature,
            global::System.Object? callback = null, global::System.Object? state = null, global::System.TimeSpan? dueTime = null, global::System.TimeSpan? period = null
        ) : ArgumentBase(_containerName, "CreateTimer", MethodSignature, InstanceName);

        public override System.Threading.ITimer CreateTimer(System.Threading.TimerCallback callback, object? state, System.TimeSpan dueTime, System.TimeSpan period){
            this._log(new CreateTimer_Arguments(_sweetMockInstanceName, "CreateTimer(System.Threading.TimerCallback, System.Object, System.TimeSpan, System.TimeSpan)", callback : callback, state : state, dueTime : dueTime, period : period));
            if (this._CreateTimer is null){
                throw new global::SweetMock.NotExplicitlyMockedException("CreateTimer", _sweetMockInstanceName);
            }
            return this._CreateTimer.Invoke(callback, state, dueTime, period);
        }

        private MockConfig.DelegateFor_CreateTimer? _CreateTimer {get;set;} = null;

        internal partial class MockConfig{
            /// <summary>
            ///    Delegate for mocking calls to <see cref="global::System.TimeProvider.CreateTimer(System.Threading.TimerCallback, System.Object, System.TimeSpan, System.TimeSpan)">TimeProvider.CreateTimer(TimerCallback, object, TimeSpan, TimeSpan)</see>.
            /// </summary>
            public delegate System.Threading.ITimer DelegateFor_CreateTimer(System.Threading.TimerCallback callback, object? state, System.TimeSpan dueTime, System.TimeSpan period);

            /// <summary>
            ///    Configures the mock to execute the specified action when calling <see cref="global::System.TimeProvider.CreateTimer(System.Threading.TimerCallback, System.Object, System.TimeSpan, System.TimeSpan)">TimeProvider.CreateTimer(TimerCallback, object, TimeSpan, TimeSpan)</see>.
            /// </summary>
            /// <param name="call">The action or function to execute when the method is called.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig CreateTimer(DelegateFor_CreateTimer call){
                target._CreateTimer = call;
                return this;
            }

            /// <summary>
            ///    Configures the mock to return a specific value, regardless of the provided arguments.
            ///    Use this to quickly define a fixed return result for <see cref="global::System.TimeProvider.CreateTimer(System.Threading.TimerCallback, System.Object, System.TimeSpan, System.TimeSpan)">TimeProvider.CreateTimer(TimerCallback, object, TimeSpan, TimeSpan)</see>.
            /// </summary>
            /// <param name="returns">The fixed value that should be returned by the mock.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig CreateTimer(System.Threading.ITimer returns)
            {
                this.CreateTimer(call: (DelegateFor_CreateTimer)((System.Threading.TimerCallback _, object? _, System.TimeSpan _, System.TimeSpan _) => returns));
                return this;
            }

            /// <summary>
            ///    Configures the mock to return one of the specific values disregarding the arguments.
            ///    Configures <see cref="global::System.TimeProvider.CreateTimer(System.Threading.TimerCallback, System.Object, System.TimeSpan, System.TimeSpan)">TimeProvider.CreateTimer(TimerCallback, object, TimeSpan, TimeSpan)</see>
            /// </summary>
            /// <param name="returnValues">The values that should be returned in order. If the values are depleted <see cref="System.InvalidOperationException"/>  is thrown.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig CreateTimer(System.Collections.Generic.IEnumerable<System.Threading.ITimer> returnValues)
            {
                var CreateTimer1_Values = returnValues.GetEnumerator();
                this.CreateTimer(call: (DelegateFor_CreateTimer)((System.Threading.TimerCallback _, object? _, System.TimeSpan _, System.TimeSpan _) => {
                    if(CreateTimer1_Values.MoveNext()){
                        return CreateTimer1_Values.Current;
                    }
                    throw new SweetMock.NotExplicitlyMockedException("CreateTimer", "TimeProvider");
                }
                ));
                return this;
            }

            /// <summary>
            ///    Configures the mock to throw the specified exception when the method is called.
            ///    Configures <see cref="global::System.TimeProvider.CreateTimer(System.Threading.TimerCallback, System.Object, System.TimeSpan, System.TimeSpan)">TimeProvider.CreateTimer(TimerCallback, object, TimeSpan, TimeSpan)</see>
            /// </summary>
            /// <param name="throws">The exception to be thrown when the method is called.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig CreateTimer(System.Exception throws)
            {
                this.CreateTimer(call: (DelegateFor_CreateTimer)((System.Threading.TimerCallback _, object? _, System.TimeSpan _, System.TimeSpan _) => throw throws));
                return this;
            }

        }
#endregion

#region Method : GetTimestamp
        public record GetTimestamp_Arguments(
            global::System.String? InstanceName,
            global::System.String MethodSignature
        ) : ArgumentBase(_containerName, "GetTimestamp", MethodSignature, InstanceName);

        public override long GetTimestamp(){
            this._log(new GetTimestamp_Arguments(_sweetMockInstanceName, "GetTimestamp()"));
            if (this._GetTimestamp is null){
                throw new global::SweetMock.NotExplicitlyMockedException("GetTimestamp", _sweetMockInstanceName);
            }
            return this._GetTimestamp.Invoke();
        }

        private MockConfig.DelegateFor_GetTimestamp? _GetTimestamp {get;set;} = null;

        internal partial class MockConfig{
            /// <summary>
            ///    Delegate for mocking calls to <see cref="global::System.TimeProvider.GetTimestamp()">TimeProvider.GetTimestamp()</see>.
            /// </summary>
            public delegate long DelegateFor_GetTimestamp();

            /// <summary>
            ///    Configures the mock to execute the specified action when calling <see cref="global::System.TimeProvider.GetTimestamp()">TimeProvider.GetTimestamp()</see>.
            /// </summary>
            /// <param name="call">The action or function to execute when the method is called.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig GetTimestamp(DelegateFor_GetTimestamp call){
                target._GetTimestamp = call;
                return this;
            }

            /// <summary>
            ///    Configures the mock to return a specific value, regardless of the provided arguments.
            ///    Use this to quickly define a fixed return result for <see cref="global::System.TimeProvider.GetTimestamp()">TimeProvider.GetTimestamp()</see>.
            /// </summary>
            /// <param name="returns">The fixed value that should be returned by the mock.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig GetTimestamp(long returns)
            {
                this.GetTimestamp(call: (DelegateFor_GetTimestamp)(() => returns));
                return this;
            }

            /// <summary>
            ///    Configures the mock to return one of the specific values disregarding the arguments.
            ///    Configures <see cref="global::System.TimeProvider.GetTimestamp()">TimeProvider.GetTimestamp()</see>
            /// </summary>
            /// <param name="returnValues">The values that should be returned in order. If the values are depleted <see cref="System.InvalidOperationException"/>  is thrown.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig GetTimestamp(System.Collections.Generic.IEnumerable<long> returnValues)
            {
                var GetTimestamp1_Values = returnValues.GetEnumerator();
                this.GetTimestamp(call: (DelegateFor_GetTimestamp)(() => {
                    if(GetTimestamp1_Values.MoveNext()){
                        return GetTimestamp1_Values.Current;
                    }
                    throw new SweetMock.NotExplicitlyMockedException("GetTimestamp", "TimeProvider");
                }
                ));
                return this;
            }

            /// <summary>
            ///    Configures the mock to throw the specified exception when the method is called.
            ///    Configures <see cref="global::System.TimeProvider.GetTimestamp()">TimeProvider.GetTimestamp()</see>
            /// </summary>
            /// <param name="throws">The exception to be thrown when the method is called.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig GetTimestamp(System.Exception throws)
            {
                this.GetTimestamp(call: (DelegateFor_GetTimestamp)(() => throw throws));
                return this;
            }

        }
#endregion

#region Method : GetUtcNow
        public record GetUtcNow_Arguments(
            global::System.String? InstanceName,
            global::System.String MethodSignature
        ) : ArgumentBase(_containerName, "GetUtcNow", MethodSignature, InstanceName);

        public override System.DateTimeOffset GetUtcNow(){
            this._log(new GetUtcNow_Arguments(_sweetMockInstanceName, "GetUtcNow()"));
            if (this._GetUtcNow is null){
                throw new global::SweetMock.NotExplicitlyMockedException("GetUtcNow", _sweetMockInstanceName);
            }
            return this._GetUtcNow.Invoke();
        }

        private MockConfig.DelegateFor_GetUtcNow? _GetUtcNow {get;set;} = null;

        internal partial class MockConfig{
            /// <summary>
            ///    Delegate for mocking calls to <see cref="global::System.TimeProvider.GetUtcNow()">TimeProvider.GetUtcNow()</see>.
            /// </summary>
            public delegate System.DateTimeOffset DelegateFor_GetUtcNow();

            /// <summary>
            ///    Configures the mock to execute the specified action when calling <see cref="global::System.TimeProvider.GetUtcNow()">TimeProvider.GetUtcNow()</see>.
            /// </summary>
            /// <param name="call">The action or function to execute when the method is called.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig GetUtcNow(DelegateFor_GetUtcNow call){
                target._GetUtcNow = call;
                return this;
            }

            /// <summary>
            ///    Configures the mock to return a specific value, regardless of the provided arguments.
            ///    Use this to quickly define a fixed return result for <see cref="global::System.TimeProvider.GetUtcNow()">TimeProvider.GetUtcNow()</see>.
            /// </summary>
            /// <param name="returns">The fixed value that should be returned by the mock.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig GetUtcNow(System.DateTimeOffset returns)
            {
                this.GetUtcNow(call: (DelegateFor_GetUtcNow)(() => returns));
                return this;
            }

            /// <summary>
            ///    Configures the mock to return one of the specific values disregarding the arguments.
            ///    Configures <see cref="global::System.TimeProvider.GetUtcNow()">TimeProvider.GetUtcNow()</see>
            /// </summary>
            /// <param name="returnValues">The values that should be returned in order. If the values are depleted <see cref="System.InvalidOperationException"/>  is thrown.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig GetUtcNow(System.Collections.Generic.IEnumerable<System.DateTimeOffset> returnValues)
            {
                var GetUtcNow1_Values = returnValues.GetEnumerator();
                this.GetUtcNow(call: (DelegateFor_GetUtcNow)(() => {
                    if(GetUtcNow1_Values.MoveNext()){
                        return GetUtcNow1_Values.Current;
                    }
                    throw new SweetMock.NotExplicitlyMockedException("GetUtcNow", "TimeProvider");
                }
                ));
                return this;
            }

            /// <summary>
            ///    Configures the mock to throw the specified exception when the method is called.
            ///    Configures <see cref="global::System.TimeProvider.GetUtcNow()">TimeProvider.GetUtcNow()</see>
            /// </summary>
            /// <param name="throws">The exception to be thrown when the method is called.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig GetUtcNow(System.Exception throws)
            {
                this.GetUtcNow(call: (DelegateFor_GetUtcNow)(() => throw throws));
                return this;
            }

        }
#endregion

#region #region Property : LocalTimeZone
        public record LocalTimeZone_Arguments(
            global::System.String? InstanceName,
            global::System.String MethodSignature,
            System.TimeZoneInfo? value = null
        ) : ArgumentBase(_containerName, "LocalTimeZone", MethodSignature, InstanceName);

        public override System.TimeZoneInfo LocalTimeZone{
            get{
                this._log(new LocalTimeZone_Arguments(_sweetMockInstanceName, "get"));
                if (this._LocalTimeZone_get is null){
                    throw new global::SweetMock.NotExplicitlyMockedException("LocalTimeZone", _sweetMockInstanceName);
                }
                return this._LocalTimeZone_get();
            }
        }
        private System.Func<System.TimeZoneInfo>? _LocalTimeZone_get { get; set; } = null;
        private System.Action<System.TimeZoneInfo>? _LocalTimeZone_set { get; set; } = null;

        internal partial class MockConfig{
            /// <summary>
            ///    Configures <see cref="global::System.TimeProvider.LocalTimeZone">TimeProvider.LocalTimeZone</see> by specifying methods to call when the property is accessed.
            /// </summary>
            /// <param name="get">Function to call when the property is read.</param>
            /// <param name="set">Function to call when the property is set.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig LocalTimeZone(System.Func<System.TimeZoneInfo> get){
                target._LocalTimeZone_get = get;
                return this;
            }
            /// <summary>
            ///    Specifies a value to use for mocking the property <see cref="global::System.TimeProvider.LocalTimeZone">TimeProvider.LocalTimeZone</see>.
            /// </summary>
            /// <param name="value">The value to use for the initial value of the property.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig LocalTimeZone(System.TimeZoneInfo value)
            {
                global::SweetMock.ValueBox<System.TimeZoneInfo> LocalTimeZone_value = new (value);
                this.LocalTimeZone(get : () => LocalTimeZone_value.Value);
                return this;
            }
        }
#endregion

#region #region Property : TimestampFrequency
        public record TimestampFrequency_Arguments(
            global::System.String? InstanceName,
            global::System.String MethodSignature,
            System.Int64? value = null
        ) : ArgumentBase(_containerName, "TimestampFrequency", MethodSignature, InstanceName);

        public override long TimestampFrequency{
            get{
                this._log(new TimestampFrequency_Arguments(_sweetMockInstanceName, "get"));
                if (this._TimestampFrequency_get is null){
                    throw new global::SweetMock.NotExplicitlyMockedException("TimestampFrequency", _sweetMockInstanceName);
                }
                return this._TimestampFrequency_get();
            }
        }
        private System.Func<long>? _TimestampFrequency_get { get; set; } = null;
        private System.Action<long>? _TimestampFrequency_set { get; set; } = null;

        internal partial class MockConfig{
            /// <summary>
            ///    Configures <see cref="global::System.TimeProvider.TimestampFrequency">TimeProvider.TimestampFrequency</see> by specifying methods to call when the property is accessed.
            /// </summary>
            /// <param name="get">Function to call when the property is read.</param>
            /// <param name="set">Function to call when the property is set.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig TimestampFrequency(System.Func<long> get){
                target._TimestampFrequency_get = get;
                return this;
            }
            /// <summary>
            ///    Specifies a value to use for mocking the property <see cref="global::System.TimeProvider.TimestampFrequency">TimeProvider.TimestampFrequency</see>.
            /// </summary>
            /// <param name="value">The value to use for the initial value of the property.</param>
            /// <returns>The updated configuration object.</returns>
            public MockConfig TimestampFrequency(long value)
            {
                global::SweetMock.ValueBox<long> TimestampFrequency_value = new (value);
                this.TimestampFrequency(get : () => TimestampFrequency_value.Value);
                return this;
            }
        }
#endregion

    }

    internal partial class MockOf_TimeProvider{
        internal class TimeProvider_Logs(CallLog log, string? instanceName = null){
            public System.Collections.Generic.IEnumerable<ArgumentBase> All() =>
                log.Calls.Where(t => instanceName == null || t.InstanceName == instanceName);

            public System.Collections.Generic.IEnumerable<MockOf_TimeProvider.TimeProvider_Arguments> TimeProvider(System.Func<MockOf_TimeProvider.TimeProvider_Arguments, bool>? filter = null) =>
                this.All().OfType<MockOf_TimeProvider.TimeProvider_Arguments>().Where(filter ?? (_ => true));

            public System.Collections.Generic.IEnumerable<MockOf_TimeProvider.CreateTimer_Arguments> CreateTimer(System.Func<MockOf_TimeProvider.CreateTimer_Arguments, bool>? filter = null) =>
                this.All().OfType<MockOf_TimeProvider.CreateTimer_Arguments>().Where(filter ?? (_ => true));

            public System.Collections.Generic.IEnumerable<MockOf_TimeProvider.GetTimestamp_Arguments> GetTimestamp(System.Func<MockOf_TimeProvider.GetTimestamp_Arguments, bool>? filter = null) =>
                this.All().OfType<MockOf_TimeProvider.GetTimestamp_Arguments>().Where(filter ?? (_ => true));

            public System.Collections.Generic.IEnumerable<MockOf_TimeProvider.GetUtcNow_Arguments> GetUtcNow(System.Func<MockOf_TimeProvider.GetUtcNow_Arguments, bool>? filter = null) =>
                this.All().OfType<MockOf_TimeProvider.GetUtcNow_Arguments>().Where(filter ?? (_ => true));

            public System.Collections.Generic.IEnumerable<MockOf_TimeProvider.LocalTimeZone_Arguments> LocalTimeZone(System.Func<MockOf_TimeProvider.LocalTimeZone_Arguments, bool>? filter = null) =>
                this.All().OfType<MockOf_TimeProvider.LocalTimeZone_Arguments>().Where(filter ?? (_ => true));

            public System.Collections.Generic.IEnumerable<MockOf_TimeProvider.TimestampFrequency_Arguments> TimestampFrequency(System.Func<MockOf_TimeProvider.TimestampFrequency_Arguments, bool>? filter = null) =>
                this.All().OfType<MockOf_TimeProvider.TimestampFrequency_Arguments>().Where(filter ?? (_ => true));
        }
    }

}
