namespace SweetMock.Generation;

using Utils;

internal partial class CodeBuilder
{
    private const bool Disable = false;

    public CodeBuilder Documentation(Action<DocumentationBuilder> build)
    {
        if (!Disable)
        {
            var t = new DocumentationBuilder(this);
            build(t);
        }

        return this;
    }

    public CodeBuilder Documentation(params string[] summary) =>
        this.Documentation(doc => doc.Summary(summary));

    public CodeBuilder AddFileHeader() =>
        this
            .Add($"// This file was auto-generated by SweetMock {SourceGeneratorMetadata.Version}")
            .Add("// Changes to this file may be lost when the code is regenerated.")
            .BR();

    public CodeBuilder AddResharperDisable() => this
        .BR()
        .Add("// ReSharper disable RedundantNameQualifier")
        .Add("// ReSharper disable RedundantNullableDirective")
        .Add("// ReSharper disable RedundantNameQualifier")
        .Add("// ReSharper disable BuiltInTypeReferenceStyle")
        .Add("// ReSharper disable InconsistentNaming").BR();

    public CodeBuilder AddGeneratedCodeAttrib() =>
        this.Add($"[System.CodeDom.Compiler.GeneratedCode(\"SweetMock\",\"{SourceGeneratorMetadata.Version}\")]");
}
